###############################################################################
#                               Model                                         #
###############################################################################

[model]

[model.mu_norm]
num_points = 25
num_sigma = 4

[model.mu_grid]
num_points = 250
half_width = 2.0
low_clip = 20.0
high_clip = 40.0


[model.priors.TFR_zeropoint]
dist = "normal"
loc = -20
scale = 2

[model.priors.TFR_slope]
dist = "normal"
loc = -9.5
scale = 2

[model.priors.TFR_curvature]
dist = "normal"
loc = 9
scale = 2

[model.priors.TFR_scatter]
dist = "jeffreys"
low = 0.01
high = 1.0

[model.priors.TFR_zeropoint_dipole]
dist = "delta"
value = [0.0, 0.0, 0.0]

[model.priors.sigma_v]
dist = "jeffreys"
low = 5
high = 2500

[model.priors.Vext]
dist = "vector_uniform"
low = 0.0
high = 1000.0


###############################################################################
#                               Inference                                     #
###############################################################################


[inference]
num_warmup = 100
num_samples = 300
num_chains = 1
seed = 42
compute_log_density = true
