[model]

[model.mu_norm]
num_points = 20
num_sigma = 5

[priors.TFR_zeropoint]
dist = "normal"
loc = -20
scale = 2

[priors.TFR_slope]
dist = "normal"
loc = -7
scale = 2

[priors.TFR_scatter]
dist = "jeffreys"
low = 0.01
high = 1.0

[priors.sigma_v]
dist = "jeffreys"
low = 5
high = 2500

[priors.Vext]
dist = "vector_uniform"
low = 0.0
high = 1000.0
