###############################################################################
#                          Priors for the TFR model                           #
###############################################################################

[TFR_zeropoint]
dist = "normal"
loc = -20
scale = 2

[TFR_slope]
dist = "normal"
loc = -7
scale = 2

###############################################################################
#                          Priors for the velocities                          #
###############################################################################

[sigma_v]
dist = "jeffreys"
low = 5
high = 2500

[Vext]
dist = "vector_uniform"
low = 0.0
high = 1000.0
