root_main = "/Users/rstiskalek/Projects/CANDEL/"
python_exec = "/Users/rstiskalek/Projects/CANDEL/venv_candel/bin/python"
machine = "local"

# root_main = "/mnt/home/rstiskalek/ceph/CANDEL"
# python_exec="/mnt/home/rstiskalek/CANDEL/venv_gpu_candel/bin/python"
# machine="rusty"


###############################################################################
#                               Inference                                     #
###############################################################################

[inference]
model = "TFR_DistMarg"
num_warmup = 500
num_samples = 500
num_chains = 1
seed = 42
compute_log_density = true
compute_evidence = true
num_chains_harmonic = 5

###############################################################################
#                           Peculiar velocity model                           #
###############################################################################

[pv_model]
use_MNR = true
# Default kind. This gets overwritten if using a submission script.
kind = "precomputed_los_Carrick2015"
# kind = "constant"
galaxy_bias = "powerlaw"


###############################################################################
#                                 Model                                       #
###############################################################################

[model]

[model.mu_norm]
num_points = 31
num_sigma = 5
low_clip = 18.0
high_clip = 42.0


[model.mag_grid]
num_sigma = 4
num_points = 25


[model.priors.h]
dist = "delta"
value = 1.0

[model.priors.alpha]
dist = "normal"
loc = 1.0
scale = 0.5

# [model.priors.b1]
# dist = "normal"
# loc = 0
# scale = 1.0
#
# [model.priors.b2]
# dist = "normal"
# loc = 0
# scale = 1.0

[model.priors.beta]
dist = "normal"
loc = 0.43
scale = 0.1

[model.priors.TFR_zeropoint]
dist = "normal"
loc = -20
scale = 2

[model.priors.TFR_slope]
dist = "normal"
loc = -9.5
scale = 2

[model.priors.TFR_curvature]
dist = "normal"
loc = 9
scale = 2

[model.priors.sigma_mu]
dist = "jeffreys"
low = 0.01
high = 2.0

[model.priors.TFR_zeropoint_dipole]
dist = "delta"
value = [0.0, 0.0, 0.0]

[model.priors.SN_absmag]
dist = "normal"
loc = -18.5
scale = 0.5

[model.priors.CL_A]
dist = "normal"
loc = -0.3
scale = 1

[model.priors.CL_B]
dist = "normal"
loc = 2
scale = 1

[model.priors.CL_C]
dist = "normal"
loc = 0
scale = 1

[model.priors.sigma_v]
dist = "jeffreys"
low = 5
high = 10_000

[model.priors.Vext]
dist = "vector_uniform"
low = 0.0
high = 5000

################################################################################
#                                  Data                                        #
################################################################################

[io]
root_output = "results"
# Default catalogue name and output path. This gets overwritten
# if using a submission script.
catalogue_name = "Clusters"
# catalogue_name = "CF4_mock_0"

fname_output = "results/test.hdf5"

[io.CF4_mock]
root = "data/CF4_mock"

add_mag_selection = true
add_eta_selection = true

[io.CF4_mock.mag_selection]
a = -0.17
m1 = 12.21
m2 = 13.9


[io.CF4_W1]
root = "data/CF4"
which_band = "w1"
best_mag_quality = true
eta_min = -0.3
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"

add_mag_selection = true
add_eta_selection = true

nsamples_subsample = "None"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.CF4_W1.mag_selection]
a = -0.16
m1 = 11.32
m2 = 13.23

[io.CF4_i]
root = "data/CF4"
which_band = "i"
best_mag_quality = true
eta_min = -0.3
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"

add_mag_selection = true
add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.CF4_i.mag_selection]
a = -0.17
m1 = 12.21
m2 = 13.9

[io.PantheonPlus]
root = "data/Pantheon+"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.Clusters]
root = "data/Clusters"
zcmb_max = 0.2

zcmb_mapping_min = 1e-5
zcmb_mapping_max = 0.3
zcmb_mapping_num_points = 1001

los_file = "data/Clusters/los_Clusters_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42


########
# Static paths to define a general acces to the catalogues and reconstruction
# fields without applying any cuts etc.
########

[io.PV_main]

[io.PV_main.CF4]
root = "data/CF4"
which_band = "i"  # Does not matter
return_all = true
los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.PV_main.PantheonPlus]
root = "data/Pantheon+"
return_all = true
los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.PV_main.Clusters]
root = "data/Clusters"
return_all = true
los_file = "data/Clusters/los_Clusters_<X>.hdf5"


[io.reconstruction_main]
rmin = 0.1
rmax = 1001
num_steps = 501

[io.reconstruction_main.Carrick2015]
path_density = "data/fields/carrick2015_twompp_density.npy"
path_velocity = "data/fields/carrick2015_twompp_velocity.npy"
