# root_main = "/Users/rstiskalek/Projects/CANDEL/"
# python_exec = "/Users/rstiskalek/Projects/CANDEL/venv_candel/bin/python"
# machine = "local"

# root_main = "/mnt/users/rstiskalek/CANDEL/"
# python_exec = "/mnt/users/rstiskalek/CANDEL/venv_candel/bin/python"
# machine = "local"


# root_main = "/mnt/home/rstiskalek/ceph/CANDEL"
# python_exec="/mnt/home/rstiskalek/CANDEL/venv_gpu_candel/bin/python"
# machine="rusty"

root_main = "/home/phys1997/CANDEL/"
root_data = "/data/phys-galsim/phys1997/CANDEL/"
python_exec = "/home/phys1997/CANDEL/venv_candel/bin/python"
machine = "arc"


###############################################################################
#                               Inference                                     #
###############################################################################

[inference]
model = "PantheonPlusModel"
shared_params = "none"

num_warmup = 1000
num_samples = 5000
num_chains = 4
chain_method = "parallel"
seed = 44
compute_log_density = true
compute_evidence = true
track_log_density_per_sample = false
num_chains_harmonic = 10

skip_if_exists = false

###############################################################################
#                           Peculiar velocity model                           #
###############################################################################

[pv_model]
# Default kind. This gets overwritten if using a submission script.
kind = "precomputed_los_Carrick2015"
# kind = "Vext"
galaxy_bias = "linear_from_beta"  # Ignored unless having an underlying density field
# galaxy_bias = "linear"  # Ignored unless having an underlying density field
which_Vext = "constant"

# (Inhomogeneus Malmquist bias settings and extrapolation), in units of Mpc / h
r_limits_malmquist = [0.1, 251]
num_points_malmquist = 251

los_decay_scale = 5.0

Vext_per_pix_nside = "none"

###############################################################################
#                                 Model                                       #
###############################################################################

[model]
Om = 0.3
use_MNR = true
marginalize_eta = true

[model.eta_grid]
k_sigma = 5
n_grid = 31

[model.priors.h]
dist = "delta"
value = 1.0
# dist = "uniform"
# low = 0.25
# high = 1.0

[model.priors.Om]
# Currently sampled only for the CF4 calibrated data.
dist = "delta"
value = 0.3
# dist = "uniform"
# low = 0.01
# high = 0.99

[model.priors.alpha]
dist = "truncated_normal"
low = 0.0
mean = 1.0
scale = 1.0

[model.priors.alpha_low]
dist = "truncated_normal"
low = 0.0
mean = 1.0
scale = 1.0

[model.priors.alpha_high]
dist = "truncated_normal"
low = 0.0
mean = 0.5
scale = 1.0

[model.priors.log_rho_t]
dist = "normal"
loc = 0.0
scale = 2.0

[model.priors.b1]
dist = "normal"
loc = 1
scale = 1.0

[model.priors.delta_b1]
dist = "normal"
loc = 0.0
scale = 0.04

[model.priors.beta]
# dist = "uniform"
# low = 0.0
# high = 2.0
dist = "normal"
loc = 0.43
scale = 0.1

[model.priors.sigma_int]
dist = "jeffreys"
low = 0.005
high = 1.0

[model.priors.sigma_log_theta]
dist = "jeffreys"
low = 0.001
high = 0.5

# TFR priors
[model.priors.TFR_zeropoint]
dist = "normal"
loc = -19.8
scale = 2.0

[model.priors.TFR_slope]
dist = "normal"
loc = -10.0
scale = 2.0

[model.priors.TFR_curvature]
dist = "normal"
loc = 10
scale = 5.0

[model.priors.zeropoint_dipole]
dist = "delta"
value = [0.0, 0.0, 0.0]
# dist = "vector_uniform_fixed"
# low = 0.0
# high = 0.3

# SN priors
[model.priors.SN_absmag]
dist = "normal"
loc = -18.5
scale = 2.0

[model.priors.SN_alpha]
dist = "normal"
loc = 0.15
scale = 1.0

[model.priors.SN_beta]
dist = "normal"
loc = 3.0
scale = 1.0


## Cluster scaling relation priors
[model.priors.CL_A]
dist = "uniform"
low = -10
high = 10

[model.priors.CL_B]
dist = "uniform"
low = -5
high = 5

[model.priors.CL_C]
dist = "uniform"
low = -5.0
high = 5.0

[model.priors.CL_C_intercept]
dist = "uniform"
low = -5.0
high = 5.0

# FP priors
[model.priors.FP_a]
dist = "normal"
loc = 1.0
scale = 1.0

[model.priors.FP_b]
dist = "normal"
loc = -1.0
scale = 1.0

[model.priors.FP_c]
dist = "normal"
loc = -1
scale = 1.0

# Velocity priors
[model.priors.sigma_v]
# dist = "jeffreys"
# low = 1
# high = 2500
dist = "maxwell"
scale = 200

[model.priors.Vext]
dist = "vector_uniform_fixed"
low = 0.0
high = 2500
# dist = "delta"
# value = [0.0, 0.0, 0.0]

[model.priors.Vext_radial]
dist = "vector_radial_uniform"
low = 0.0
high = 5000

rknot = [0, 250, 600]
method = "cubic"

[model.priors.Vext_sigma]
dist = "uniform"
low = 1
high = 10_000

[model.priors.Rdust]
# 0.19 +- 0.01 for W1. For W2 should be 0.15 +- 0.01. I take it a little bit
# larger to be conservative.
dist = "normal"
loc = 0.19
scale = 0.05

[model.priors.R_dist_emp]
dist = "uniform"
low = 1.0
high = 300

[model.priors.p_dist_emp]
dist = "truncated_normal"
low = 0.0
mean = 2.0
scale = 0.1

[model.priors.n_dist_emp]
dist = "truncated_normal"
low = 0.0
mean = 1.0
scale = 30

################################################################################
#                                  Data                                        #
################################################################################

[io]
root_output = "results"
# Default catalogue name and output path. This gets overwritten
# if using a submission script.
# catalogue_name = ["CF4_W1", "CF4_i"]
catalogue_name = "PantheonPlusLane"
fname_output = "results/test.hdf5"


[io.CF4_mock]
root = "data/CF4_mock"
add_eta_selection = true


[io.CF4_W1]
root = "data/CF4"
which_band = "w1"
best_mag_quality = true
eta_min = -0.3
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"
dust_model = "none"

add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"


[io.CF4_i]
root = "data/CF4"
which_band = "i"
best_mag_quality = true
eta_min = -0.3
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"

exclude_W1 = false

add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"


[io.2MTF]
root = "data/2MTF"
eta_min = -0.1
eta_max = 0.2

zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/2MTF/los_2MTF_<X>.hdf5"

[io.SFI]
root = "data/SFI"
eta_min = -0.1

zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/SFI/los_SFI_<X>.hdf5"

[io.Foundation]
root = "data/Foundation"

zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/Foundation/los_Foundation_<X>.hdf5"

[io.LOSS]
root = "data/LOSS"

zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/LOSS/los_LOSS_<X>.hdf5"

[io.PantheonPlus]
root = "data/Pantheon+"
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.PantheonPlusLane]
root = "data/Pantheon+_Lane"
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/Pantheon+_Lane/los_CF4_PantheonPlusLane_<X>.hdf5"

[io.Clusters]
root = "data/Clusters"
zcmb_max = 0.2
which_relation = "LT"
finite_logY = true
convert_to_CMB_frame = true

los_file = "data/Clusters/los_Clusters_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42

[io.SDSS_FP]
root = "data/SDSS"
zcmb_min = "none"
zcmb_max = 0.05

los_file = "data/SDSS/los_SDSS_FP_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42

[io.6dF_FP]
root = "data/6dF_FP"
which_band = "J"
zcmb_min = "none"
zcmb_max = 0.05

los_file = "data/6dF_FP/los_6dF_FP_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42


[io.CF4_calibrated]
root = "data/CF4_calibrated"
zcmb_min = "none"
zcmb_max = "none"
b_min = "none"

nsamples_subsample = "none"
seed_subsample = 42


################################################################################
#                         Redshift2real mapping                                #
################################################################################

[redshift2real]

which_calibration = "none"
which_reconstruction = "Carrick2015"

# "/Users/rstiskalek/Projects/CANDEL/results/VFO/precomputed_los_Carrick2015_CF4_W1_MNR_linear.hdf5"


########
# Static paths to define a general acces to the catalogues and reconstruction
# fields without applying any cuts etc.
########

[io.PV_main]

[io.PV_main.CF4]
root = "data/CF4"
which_band = "i"  # Does not matter
return_all = true
los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.PV_main.2MTF]
root = "data/2MTF"
return_all = true
los_file = "data/2MTF/los_2MTF_<X>.hdf5"

[io.PV_main.SFI]
root = "data/SFI"
return_all = true
los_file = "data/SFI/los_SFI_<X>.hdf5"

[io.PV_main.Foundation]
root = "data/Foundation"
return_all = true
los_file = "data/Foundation/los_Foundation_<X>.hdf5"

[io.PV_main.LOSS]
root = "data/LOSS"
return_all = true
los_file = "data/LOSS/los_LOSS_<X>.hdf5"

[io.PV_main.PantheonPlus]
root = "data/Pantheon+"
return_all = true
los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.PV_main.PantheonPlusLane]
root = "data/Pantheon+_Lane"
return_all = true
los_file = "data/Pantheon+_Lane/los_CF4_PantheonPlusLane_<X>.hdf5"

[io.PV_main.Clusters]
root = "data/Clusters"
return_all = true
los_file = "data/Clusters/los_Clusters_<X>.hdf5"

[io.PV_main.SDSS_FP]
root = "data/SDSS"
return_all = true
los_file = "data/SDSS/los_SDSS_FP_<X>.hdf5"

[io.PV_main.6dF_FP]
root = "data/6dF_FP"
return_all = true
los_file = "data/6dF_FP/los_6dF_FP_<X>.hdf5"

[io.PV_main.CF4_HQ]
root = "data/CF4_HQ"
los_file = "data/CF4_HQ/los_CF4_HQ_<X>.hdf5"

[io.reconstruction_main]
# Distance over which to interpolate the 3D grids along the source LOS.
rmin = 0.001
rmax = 201
num_steps = 251

[io.reconstruction_main.manticore_2MPP_MULTIBIN_N256_DES_V2]
fpath_root = "/mnt/extraspace/rstiskalek/MANTICORE/2MPP_MULTIBIN_N256_DES_V2/sph_fields_new_feb/sph_fields"

[io.reconstruction_main.Carrick2015]
path_density = "data/fields/carrick2015_twompp_density.npy"
path_velocity = "data/fields/carrick2015_twompp_velocity.npy"

[io.reconstruction_main.Lilow2024]
path_density = "/mnt/extraspace/rstiskalek/catalogs/Lilow2024_density.npy"
path_velocity_x = "/mnt/extraspace/rstiskalek/catalogs/Lilow2024_xVelocity.npy"
path_velocity_y = "/mnt/extraspace/rstiskalek/catalogs/Lilow2024_yVelocity.npy"
path_velocity_z = "/mnt/extraspace/rstiskalek/catalogs/Lilow2024_zVelocity.npy"

[io.reconstruction_main.CF4]
folder = "/mnt/extraspace/rstiskalek/catalogs/CF4/CF4gp_23avr24_256-z008_test_100_realizations"

[io.reconstruction_main.CLONES]
file_path = "/mnt/extraspace/rstiskalek/CLONES/s8/cf2gvpecc1pt5elmo73_sig6distribsbvoldi_RZA3Derrv2_512_500_ss8_zinit60_000.hdf5"

[io.reconstruction_main.HAMLET_V0]
fpath_root = "/mnt/extraspace/rstiskalek/catalogs/HAMLET/HAMLET_V0"
version = 0

[io.reconstruction_main.HAMLET_V1]
fpath_root = "/mnt/extraspace/rstiskalek/catalogs/HAMLET/HAMLET_V1"
version = 1

[io.reconstruction_main.CB1]
fpath_root = "/mnt/extraspace/rstiskalek/csiborg1/field"
version = "csiborg1"

[io.reconstruction_main.CB2]
fpath_root = "/mnt/extraspace/rstiskalek/csiborg2_main/field"
version = "csiborg2"
