root_main = "/Users/rstiskalek/Projects/CANDEL/"
python_exec = "/Users/rstiskalek/Projects/CANDEL/venv_candel/bin/python"
machine = "local"

# root_main = "/Users/yasin/code/CANDEL/"
# python_exec = "/Users/yasin/code/CANDEL/venv_candel/bin/python"
# machine = "local"

# root_main = "/mnt/home/rstiskalek/ceph/CANDEL"
# python_exec="/mnt/home/rstiskalek/CANDEL/venv_gpu_candel/bin/python"
# machine="rusty"


###############################################################################
#                               Inference                                     #
###############################################################################

[inference]
model = "TFRModel_DistMarg"
shared_params = "none"

# model = "PantheonPlusModel_DistMarg"
num_warmup = 1500
num_samples = 15000
num_chains = 1
seed = 42
compute_log_density = true
compute_evidence = true
num_chains_harmonic = 5

skip_if_exists = false

###############################################################################
#                           Peculiar velocity model                           #
###############################################################################

[pv_model]
use_MNR = false
# Default kind. This gets overwritten if using a submission script.
kind = "precomputed_los_Carrick2015"
# kind = "Vext"
galaxy_bias = "powerlaw"  # Ignored unless having an underlying density field

###############################################################################
#                                 Model                                       #
###############################################################################

[model]

[model.mu_norm]
num_points = 31
num_sigma = 5
low_clip = 18.0
high_clip = 42.0

[model.mag_grid]
num_sigma = 4
num_points = 25

[model.priors.h]
dist = "delta"
value = 1.0

[model.priors.alpha]
dist = "normal"
loc = 1.0
scale = 1.0

[model.priors.b1]
dist = "normal"
loc = 0
scale = 1.0

[model.priors.beta]
dist = "uniform"
low = 0.0
high = 2.0

[model.priors.sigma_mu]
dist = "jeffreys"
low = 0.005
high = 1.0

# TFR priors

[model.priors.TFR_zeropoint]
dist = "normal"
loc = -19.8
scale = 2.0

[model.priors.TFR_slope]
dist = "normal"
loc = -10.0
scale = 2.0

[model.priors.TFR_curvature]
dist = "normal"
loc = 10
scale = 5.0

[model.priors.TFR_zeropoint_dipole]
dist = "delta"
value = [0.0, 0.0, 0.0]

# SN priors

[model.priors.SN_absmag]
dist = "normal"
loc = -18.5
scale = 0.5

[model.priors.SN_absmag_dipole]
dist = "vector_uniform"
low = 0.0
high = 0.25

## Cluster scaling relation priors

[model.priors.CL_A]
dist = "uniform"
low = -5
high = 10

[model.priors.CL_B]
dist = "uniform"
low = 0
high = 10

[model.priors.CL_C]
dist = "uniform"
low = -2.0
high = 2.0

# FP priors

[model.priors.FP_a]
dist = "normal"
loc = 1.0
scale = 1.0

[model.priors.FP_b]
dist = "normal"
loc = -1.0
scale = 1.0

[model.priors.FP_c]
dist = "normal"
loc = -1
scale = 1.0

# Velocity priors

[model.priors.sigma_v]
dist = "jeffreys"
low = 5
high = 2500

[model.priors.Vext]
dist = "vector_uniform_fixed"
low = 0.0
high = 2500

[model.priors.Vext_radial]
dist = "vector_radial_spline_uniform"
low = 0.0
high = 5000

rknot = [0, 250, 600]
k = 1
endpoints="not-a-knot"

[model.priors.Rdust]
# 0.19 +- 0.01 for W1. For W2 should be 0.15 +- 0.01. I take it a little bit
# larger to be conservative.
dist = "normal"
loc = 0.19
scale = 0.05

################################################################################
#                                  Data                                        #
################################################################################

[io]
root_output = "results"
# Default catalogue name and output path. This gets overwritten
# if using a submission script.
catalogue_name = ["CF4_W1", "CF4_i"]
# catalogue_name = "CF4_W1"

fname_output = "results/test.hdf5"

[io.CF4_mock]
root = "data/CF4_mock"

add_mag_selection = true
add_eta_selection = true

[io.CF4_mock.mag_selection]
a = -0.17
m1 = 12.21
m2 = 13.9


[io.CF4_W1]
root = "data/CF4"
which_band = "w1"
best_mag_quality = true
eta_min = -0.3
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"
dust_model = "none"

add_mag_selection = true
add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.CF4_W1.mag_selection]
a = -0.16
m1 = 11.32
m2 = 13.23

[io.CF4_i]
root = "data/CF4"
which_band = "i"
best_mag_quality = true
eta_min = -0.3
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"

exclude_w1 = false

add_mag_selection = true
add_eta_selection = true

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.CF4_i.mag_selection]
a = -0.17
m1 = 12.21
m2 = 13.9

[io.PantheonPlus]
root = "data/Pantheon+"
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5

nsamples_subsample = "none"
seed_subsample = 42

los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.Clusters]
root = "data/Clusters"
zcmb_max = 0.2
which_relation = "LT"

zcmb_mapping_min = 1e-5
zcmb_mapping_max = 0.3
zcmb_mapping_num_points = 1001

los_file = "data/Clusters/los_Clusters_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42

[io.SDSS_FP]
root = "data/SDSS"
zcmb_min = "none"
zcmb_max = 0.05

los_file = "data/SDSS/los_SDSS_FP_<X>.hdf5"

nsamples_subsample = "none"
seed_subsample = 42


########
# Static paths to define a general acces to the catalogues and reconstruction
# fields without applying any cuts etc.
########

[io.PV_main]

[io.PV_main.CF4]
root = "data/CF4"
which_band = "i"  # Does not matter
return_all = true
los_file = "data/CF4/los_CF4_TFR_<X>_OLD.hdf5"

[io.PV_main.PantheonPlus]
root = "data/Pantheon+"
return_all = true
los_file = "data/Pantheon+/los_CF4_Pantheon+_<X>.hdf5"

[io.PV_main.Clusters]
root = "data/Clusters"
return_all = true
los_file = "data/Clusters/los_Clusters_<X>.hdf5"

[io.PV_main.SDSS_FP]
root = "data/SDSS"
return_all = true
los_file = "data/SDSS/los_SDSS_FP_<X>.hdf5"


[io.reconstruction_main]
rmin = 0.1
rmax = 751
num_steps = 501

[io.reconstruction_main.Carrick2015]
path_density = "data/fields/carrick2015_twompp_density.npy"
path_velocity = "data/fields/carrick2015_twompp_velocity.npy"
