root_main = "/Users/rstiskalek/Projects/CANDEL/"

###############################################################################
#                               Inference                                     #
###############################################################################

[inference]
model = "TFRModel"
num_warmup = 500
num_samples = 500
num_chains = 1
seed = 42
compute_log_density = true
compute_evidence = true
num_chains_harmonic = 5

###############################################################################
#                           Peculiar velocity model                           #
###############################################################################

[pv_model]
use_MNR = false

# Default kind. This gets overwritten if using a submission script.
kind = "precomputed_los_Carrick2015"



###############################################################################
#                                 Model                                       #
###############################################################################

[model]

[model.mu_norm]
num_points = 25
num_sigma = 6
low_clip = 20
high_clip = 40

[model.r_grid]
num_mu_sigma = 4
num_vel_sigma = 4
num_points = 51
low_clip_mu = 20.0
high_clip_mu = 42.5
low_clip_dist = 0.1
max_clip_dist = 1000

[model.mag_grid]
num_sigma = 4
num_points = 25


[model.priors.h]
dist = "delta"
value = 1.0

[model.priors.alpha]
dist = "normal"
loc = 1.0
scale = 0.5


[model.priors.beta]
dist = "normal"
loc = 0.43
scale = 0.1

[model.priors.TFR_zeropoint]
dist = "normal"
loc = -20
scale = 2

[model.priors.TFR_slope]
dist = "normal"
loc = -9.5
scale = 2

[model.priors.TFR_curvature]
dist = "normal"
loc = 9
scale = 2

[model.priors.TFR_scatter]
dist = "jeffreys"
low = 0.01
high = 1.0

[model.priors.TFR_zeropoint_dipole]
dist = "delta"
value = [0.0, 0.0, 0.0]

[model.priors.sigma_v]
dist = "jeffreys"
low = 5
high = 2500

[model.priors.Vext]
dist = "vector_uniform"
low = 0.0
high = 1000.0

################################################################################
#                                  Data                                        #
################################################################################

[io]
root_output = "results"
# Default catalogue name and output path. This gets overwritten
# if using a submission script.
catalogue_name = "CF4_W1"
fname_output = "results/test.hdf5"

[io.CF4_W1]
root = "data/CF4"
which_band = "w1"
best_mag_quality = true
eta_min = -0.3
zcmb_max = 0.05
b_min = 7.5
remove_outliers = true
calibration = "None"

add_mag_selection = false
add_eta_selection = false

nsamples_subsample = 100
seed_subsample = 42

los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.CF4_W1.mag_selection]
a = -0.16
m1 = 11.32
m2 = 13.23


########
# Static paths to define a general acces to the catalogues and reconstruction
# fields without applying any cuts etc.
########

[io.PV_main]

[io.PV_main.CF4]
root = "data/CF4"
which_band = "i"  # Does not matter
return_all = true
los_file = "data/CF4/los_CF4_TFR_<X>.hdf5"

[io.reconstruction_main]
rmin = 0
rmax = 200
num_steps = 250

[io.reconstruction_main.Carrick2015]
path_density = "data/fields/carrick2015_twompp_density.npy"
path_velocity = "data/fields/carrick2015_twompp_velocity.npy"
