[inference]
sampler = "nss"
seed = 42
num_warmup = 1000
num_samples = 1000
num_chains = 1
chain_method = "sequential"
dense_mass_blocks = [
    [
        "H0",
        "D_c",
        "eta",
        "dv_sys",
        "i0",
        "di_dr",
        "Omega0",
        "dOmega_dr",
        "x0",
        "y0",
    ],
    [
        "sigma_v_sys",
        "sigma_y_floor",
        "sigma_a_floor",
        "sigma_x_floor",
    ],
]
init_maxiter = 0
init_method = "config"
max_tree_depth = 10
n_live = 5000
num_mcmc_steps = 0
num_delete = 250
termination = -3

[model]
which_run = "maser_disk"
Om = 0.315
galaxy = "NGC5765b"
use_selection = false
use_clump_weight = false
clump_galaxies = [
    "NGC5765b",
    "NGC6264",
    "NGC6323",
]
marginalise_r = true
sigma_v_default = 0.25
D_c_prior = "volume"
R_phys_lo = 0.01
R_phys_hi = 2.0

[model.priors.H0]
dist = "uniform"
low = 10.0
high = 200.0

[model.priors.sigma_pec]
dist = "delta"
value = 300

[model.priors.eta]
dist = "uniform"
low = 3.0
high = 9.0

[model.priors.dv_sys]
dist = "normal"
loc = 0.0
scale = 300.0

[model.priors.x0]
dist = "normal"
loc = 0.0
scale = 500.0

[model.priors.y0]
dist = "normal"
loc = 0.0
scale = 500.0

[model.priors.i0]
dist = "sine_angle"
low = 60.0
high = 110.0

[model.priors.Omega0]
dist = "uniform"
low = 0.0
high = 360.0

[model.priors.dOmega_dr]
dist = "uniform"
low = -30.0
high = 30.0

[model.priors.di_dr]
dist = "uniform"
low = -30.0
high = 30.0

[model.priors.d2i_dr2]
dist = "uniform"
low = -30.0
high = 30.0

[model.priors.d2Omega_dr2]
dist = "uniform"
low = -30.0
high = 30.0

[model.priors.sigma_x_floor]
dist = "truncated_normal"
mean = 10.0
scale = 5.0
low = 0.0
high = 100.0

[model.priors.sigma_y_floor]
dist = "truncated_normal"
mean = 10.0
scale = 5.0
low = 0.0
high = 100.0

[model.priors.sigma_v_sys]
dist = "truncated_normal"
mean = 2.0
scale = 1.0
low = 0.0
high = 100.0

[model.priors.sigma_v_hv]
dist = "truncated_normal"
mean = 2.0
scale = 1.0
low = 0.0
high = 100.0

[model.priors.sigma_a_floor]
dist = "truncated_normal"
mean = 0.3
scale = 0.15
low = 0.0
high = 0.75

[model.priors.ecc]
dist = "uniform"
low = 0.0
high = 0.5

[model.priors.periapsis]
dist = "uniform"
low = 0.0
high = 360.0

[model.priors.dperiapsis_dr]
dist = "uniform"
low = -180.0
high = 180.0

[model.priors.D_lim]
dist = "uniform"
low = 50.0
high = 300.0

[model.priors.D_width]
dist = "uniform"
low = 5.0
high = 100.0

[model.galaxies.CGCG074-064]
ra = 210.768491
dec = 8.947582
v_sys_obs = 7175
D_lo = 66.0
D_hi = 150.0

[model.galaxies.CGCG074-064.init]
H0 = 79.8946
D_c = 89.2701
eta = 5.4411
x0 = 1.3965
y0 = 6.4031
i0 = 90.6023
Omega0 = 101.468
dOmega_dr = 4.7988
di_dr = -1.8697
sigma_x_floor = 0.35
sigma_y_floor = 14.2729
sigma_v_sys = 1.8223
sigma_v_hv = 2.0683
sigma_a_floor = 0.2378
dv_sys = -265.5389

[model.galaxies.NGC4258]
ra = 184.74009
dec = 47.30372
v_sys_obs = 667
D_lo = 4.0
D_hi = 10.0
use_ecc = true
use_quadratic_warp = true
use_float64 = true
marginalise_r = false
phi_method = "bruteforce"
n_phi_sys = 50001
n_phi_red = 30001
n_phi_blue = 20001
phi_range_sys_deg = [-90, 90]
phi_range_red_deg = [0, 180]
phi_range_blue_deg = [180, 360]
r_ang_ref = 6.1

[model.galaxies.NGC4258.init]
H0 = 73.0
D_c = 7.593
eta = 6.72
x0 = -152.0
y0 = 556.0
i0 = 87.05
di_dr = 2.59
d2i_dr2 = 0.041
Omega0 = 88.43
dOmega_dr = 2.21
d2Omega_dr2 = -0.13
ecc = 0.007
periapsis = 318.0
dperiapsis_dr = 123.0
sigma_x_floor = 1.6
sigma_y_floor = 4.1
sigma_v_sys = 0.31
sigma_v_hv = 2.25
sigma_a_floor = 0.46
dv_sys = -193.7

[model.galaxies.NGC5765b]
ra = 222.71461
dec = 5.11449
v_sys_obs = 8465
D_lo = 85.0
D_hi = 200.0

[model.galaxies.NGC5765b.init]
H0 = 68.1294
D_c = 123.4795
eta = 5.5729
x0 = -44.8896
y0 = -99.1145
i0 = 84.9224
Omega0 = 146.83
dOmega_dr = -3.2848
di_dr = 11.6208
sigma_x_floor = 10.1172
sigma_y_floor = 3.4971
sigma_v_sys = 1.8661
sigma_v_hv = 2.8261
sigma_a_floor = 0.0798
dv_sys = -131.1467

[model.galaxies.NGC6264]
ra = 254.3172
dec = 27.8496
v_sys_obs = 10145
D_lo = 70.0
D_hi = 250.0

[model.galaxies.NGC6264.init]
H0 = 62.6426
D_c = 160.7498
eta = 5.3226
x0 = 4.166
y0 = 6.9749
i0 = 90.3963
Omega0 = 94.2117
dOmega_dr = 18.4692
di_dr = -1.2975
sigma_x_floor = 0.6085
sigma_y_floor = 5.4471
sigma_v_sys = 1.6202
sigma_v_hv = 2.9953
sigma_a_floor = 0.1373
dv_sys = 66.4503

[model.galaxies.NGC6323]
ra = 258.32519
dec = 43.78244
v_sys_obs = 7662
D_lo = 60.0
D_hi = 350.0

[model.galaxies.NGC6323.init]
H0 = 50.4354
D_c = 151.1639
eta = 4.9678
x0 = 14.5012
y0 = 3.3823
i0 = 91.8349
Omega0 = 189.5905
dOmega_dr = 13.8031
di_dr = -1.1693
sigma_x_floor = 3.978
sigma_y_floor = 2.4919
sigma_v_sys = 1.8041
sigma_v_hv = 1.698
sigma_a_floor = 0.1486
dv_sys = 190.3925

[model.galaxies.UGC3789]
ra = 109.87872
dec = 59.35513
v_sys_obs = 3245
D_lo = 10.0
D_hi = 100.0

[model.galaxies.UGC3789.init]
H0 = 64.5287
D_c = 50.7209
eta = 5.3635
x0 = -402.2705
y0 = -461.1638
i0 = 85.6441
Omega0 = 222.9669
dOmega_dr = -3.2655
di_dr = 8.1005
sigma_x_floor = 4.6195
sigma_y_floor = 7.5683
sigma_v_sys = 0.0175
sigma_v_hv = 2.0618
sigma_a_floor = 0.279
dv_sys = 15.2498

[optimise]
H0_for_D_estimate = 70.0
D_sobol_sigma_v = 500.0
D_sobol_n_sigma = 5
max_generations = 5000

[joint.priors.sigma_pec]
dist = "maxwell"
scale = 156.7

[io]
root_output = "results/Megamaser"

[io.maser_data]
root = "data/Megamaser"
